#General settings
[general]
	#Enables ingame rewards on first spawn for Patreons
	patreon_rewards = true

#Blocks
[blocks]
	#Change the effect duration of the charged gem blocks
	# Default: 300
	# Range: 10 ~ 10000
	charged_block_effect_duration = 300
	#Change the effect amplifier of the charged gem blocks
	# Default: 0
	# Range: 0 ~ 5
	charged_block_effect_amplifier = 0

#Items
[gems]
	#Enable or disable if the amulets should get a durability
	is_amulet_destroyable = false
	#Change the effect duration of the amulets
	# Default: 200
	# Range: 10 ~ 10000
	amulet_effect_duration = 200
	#Change the effect amplifier of the amulets
	# Default: 0
	# Range: 0 ~ 5
	amulet_effect_amplifier = 0
	#Change the effect radius of the amulets
	# Default: 3
	# Range: 1 ~ 10
	amulet_effect_radius = 3
	#Change the effect cooldown after the usage
	# Default: 600
	# Range: 0 ~ 10000
	amulet_effect_cooldown = 600
	#Change the maximum usages of the amulets
	# Default: 100
	# Range: 1 ~ 1000
	amulet_max_usages = 100
	#Change the amount of experience levels you need to charge a gem on the gem charger
	# Default: 25
	# Range: 1 ~ 50
	charging_cost = 25
	#Should the pickaxes have a mining level of diamond or iron? 1 = diamond, 0 = iron
	# Default: 1
	# Range: 0 ~ 1
	mining_level = 1

#World
[world]
	#Enable or disable the dungeon loot generator
	loot_generator = true
